/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the <GL/glext.h> header file. */
/* #undef HAVE_GL_GLEXT_H */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Lua support is enabled */
/* #undef HAVE_LUA */

/* Define to 1 if you have the <lualib.h> header file. */
#define HAVE_LUALIB_H 1

/* Define to 1 if you have the <lua.h> header file. */
#define HAVE_LUA_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* OpenGL support is enabled */
/* #undef HAVE_OPENGL */

/* SDL_image support is enabled */
/* #undef HAVE_SDL_IMAGE */

/* Define to 1 if you have the <SDL_image.h> header file. */
#define HAVE_SDL_IMAGE_H 1

/* SDL_net support is enabled */
#define HAVE_SDL_NET 1

/* Define to 1 if you have the <SDL_net.h> header file. */
#define HAVE_SDL_NET_H 1

/* SDL_sound support is enabled */
/* #undef HAVE_SDL_SOUND */

/* Define to 1 if you have the <SDL_sound.h> header file. */
/* #undef HAVE_SDL_SOUND_H */

/* snprintf() is available */
#define HAVE_SNPRINTF 1

/* Define to 1 if you have the <speex.h> header file. */
/* #undef HAVE_SPEEX_H */

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* vsnprintf() is available */
#define HAVE_VSNPRINTF 1

/* Name of package */
#define PACKAGE "AlephOne"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "http://sourceforge.net/bugs/?group_id=1997"

/* Define to the full name of this package. */
#define PACKAGE_NAME "Aleph One/SDL"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Aleph One/SDL 20051119"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "AlephOne"

/* Define to the version of this package. */
#define PACKAGE_VERSION "20051119"

/* Speex support is enabled */
/* #undef SPEEX */

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Target platform name */
#define TARGET_PLATFORM "linux-gnu arm"

/* Version number of package */
#define VERSION "20051119"

/* Win32 music is disabled */
/* #undef WIN32_DISABLE_MUSIC */
